spring:
  application:
    name: CH04
  datasource:
    url: jdbc:mysql://localhost:3306/CH04_SPRINGDATAJPA?serverTimezone=UTC
    username: springstudent
    password: springstudent
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: com.example.CH04.namingStrategy.CENamingStrategy